//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trojan.TrojanDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public int AttributeId { get; set; }
        public string AttributeName { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public int F_in { get; set; }
        public int F_out { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual VirusDescriptionItems VirusDescriptionItem { get; set; }
    }
}
