//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trojan.TrojanDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Virus
    {
        public int Virus_Id { get; set; }
        public string name { get; set; }
        public int UserUser_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Matrix Matrix { get; set; }
    }
}
