//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trojan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matrix_Cell
    {
        public int Cell_Id { get; set; }
        public short RowId { get; set; }
        public short ColumnId { get; set; }
        public Nullable<bool> value { get; set; }
        public string submatrix { get; set; }
        public int MatrixMatrix_Id { get; set; }
    
        public virtual Matrix Matrix { get; set; }
    }
}
