//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trojan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matrix
    {
        public Matrix()
        {
            this.Matrix_Cell = new HashSet<Matrix_Cell>();
        }
    
        public int Matrix_Id { get; set; }
        public string name { get; set; }
    
        public virtual Virus Vir { get; set; }
        public virtual ICollection<Matrix_Cell> Matrix_Cell { get; set; }
    }
}
