//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trojan.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrojanDBContext : DbContext
    {
        public TrojanDBContext()
            : base("name=TrojanDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Virus> Virus { get; set; }
        public virtual DbSet<Matrix> Matrices { get; set; }
        public virtual DbSet<Matrix_Cell> Matrix_Cell { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<VirusDescriptionItems> VirusDescriptionItems { get; set; }
    }
}
