//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trojan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirusDescriptionItems
    {
        public string ItemId { get; set; }
        public string VirusId { get; set; }
        public bool On_Off { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int AttributeId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Attribute Attrib { get; set; }
    }
}
